spring.application.name=ToDo-API

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=recyclebin

spring.jpa.hibernate.ddl-auto=update
